# site title
title: Just Do IT

# user name or organization name
user: zhiyue

# issue repository
repository: note

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: b#405e529a2d1dd9e3dc44d656ef55bf1b0f9b5c4

# posts per page
perpage: 20


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
